version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: grpcdms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: something
    ports:
      - "5433:5433"
  grpc_server:
    build:
      context: ./server
    ports:
      - "50051:50051"
    depends_on:
      - postgres
  fastapi_client:
    build:
      context: ./consumer
    ports:
      - "8000:8000"
    depends_on:
      - grpc_server
